[theme]
base="light"

[server]
headless = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[branding]
appName = "Bayesian False Positive Estimator"
favicon = "📊"  # Optional emoji or link to a favicon
